name: Release | Docker
on:
  workflow_dispatch:
    inputs:
      IMAGE_VERSION:
        required: true
        type: string
        description: Created image tag
jobs:
  deploy_to_docker:
    environment: docker
    runs-on: ubuntu-22.04
    name: Deploy to docker
    steps:
      - name: "Checkout git"
        uses: actions/checkout@v2
      - name: "Build image"
        run: docker build -t przemekcloudity/prettier-apex-server:latest .
      - name: "Tag version"
        env:
          VERSION: ${{ github.event.inputs.IMAGE_VERSION }}
        run: docker tag przemekcloudity/prettier-apex-server:latest przemekcloudity/prettier-apex-server:$VERSION
      - name: "Authorize to docker hub"
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login --username przemekcloudity --password-stdin
      - name: "Push tags to docker"
        run: docker push -a przemekcloudity/prettier-apex-server
